### ISSUE TITLE
custom mail to user after confirm

### ISSUE THREAD

**Issue by p-view** [eliashaeussler/typo3-form-consent#11]
A custom mail to user after confirm would be cool. A mail with individual test after the Opt-in like the "mail to user" finisher.
(compare to  powermail)

**Comment by eliashaeussler** [comment]
Thanks for your issue. This is a feature I always wanted to implement, but did not have the time yet. If you like, you can provide a PR and I will have a look. Otherwise, give me some time please.

**Comment by eliashaeussler** [comment]
@p-view Until this gets implemented, you can write an EventListener for the [`ApproveConsentEvent`](https://github.com/eliashaeussler/typo3-form-consent/blob/master/Classes/Event/ApproveConsentEvent.php) and send the e-mail by your own.

You can access the e-mail address by `$event->getConsent->getEmail()`.

**Comment by eliashaeussler** [comment]
Hi @p-view, I finally found some time and implemented a way that finishers can be executed after a user gave his consent. I'd be happy if you can try it out. Here are the instructions: https://github.com/eliashaeussler/typo3-form-consent/tree/feature/post-approval-finishers#invoke-finishers-on-consent-approval

Just run `composer require eliashaeussler/typo3-form-consent:dev-feature/post-approval-finishers` to get the feature. Note that the branch contains some breaking changes, so if something does no longer work, just ping me.

**Comment by eliashaeussler** [comment]
FYI: This feature is now part of version 0.3.0.
