### ISSUE TITLE
[BUG] automatic consent approval/dismissal by mail providers

### ISSUE THREAD

**Issue by avcfi** [eliashaeussler/typo3-form-consent#238]
### TYPO3 version

11.5.37

### PHP version

8.1.28

### Extension version

2.2.0

### Composer mode

- [X] I'm running TYPO3 in composer mode.

### Operating system

Unix

### Current behavior

Receiving the approval/dismissal mail results in - in my case - Outlook testing the link and approving/dismissing the consent.

### Expected behavior

The consent plugin should check for such testing behaviour and in such case not approve/dismiss the consent.
Another way would be not to have a direct response but rather a second CTA on the requested page that explicitely approves/dismisses. 

### Steps to reproduce

1. Submit a form using form_consent (preferably outlook mail)
2. Open the consent mail and wait for the mail provider to check the link

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by eliashaeussler** [comment]
Hi @avcfi, thanks for the issue. This is a totally valid use case and I'll definitely implement a solution for it. Unfortunately, my time is very limited at the moment, so it'll take a little bit until this is done.

**Comment by eliashaeussler** [comment]
Hi @avcfi, I implemented a new feature in #272 to address this issue and released it with [`2.3.0`](https://github.com/eliashaeussler/typo3-form-consent/releases/tag/2.3.0).
