### ISSUE TITLE
[FEATURE] Return lastInsertId

### ISSUE THREAD

**Issue by DavidBruchmann** [eliashaeussler/typo3-form-consent#61]
### Is your feature request related to a problem?

When the consent table is saved it's currently not possible to fill additional table fields. The existing Event Handlers never offer a solution for this challenge.

### Describe the solution you'd like

I'd like two solutions, one I describe in this issue:
I'd like to get the lastInsertId from the form_consent to be available, so that an update per form configuration in the yaml file could be realized.

### Describe alternatives you've considered

See the next issue I'll create.

### Additional context

Example for configurable update action:  

![image](https://user-images.githubusercontent.com/999146/174792681-3d6c4995-fb0d-4c65-bc10-ab1b4fda20a8.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by eliashaeussler** [comment]
@DavidBruchmann Thank for your issue.

I just implemented this with

- #64 

and will publish a new release soonish.

**Comment by DavidBruchmann** [comment]
great, thanks a lot!
Didn't test it yet but expect it will work :)

**Comment by eliashaeussler** [comment]
Released with [`0.6.0`](https://github.com/eliashaeussler/typo3-form-consent/releases/tag/0.6.0).
