### ISSUE TITLE
[BUG] Upgradewizard-Error

### ISSUE THREAD

**Issue by IngoMueller** [eliashaeussler/typo3-form-consent#79]
### TYPO3 version

11.5.17

### PHP version

8.1.9

### Extension version

0.6.3

### Composer mode

- [X] I'm running TYPO3 in composer mode.

### Operating system

Apache

### Current behavior

Hey Elias,

i have a strange behavior. If i run the Upgradewizard and updates are already done, i got a Error:
```
Starting migration of record "tx_formconsent_domain_model_consent.1"...
Failed
```

How can i resolve this?

Cheers, Ingo

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by eliashaeussler** [comment]
Hi @IngoMueller, thanks for your issue. This is now resolved and released with `0.6.4`.
